---
Name: ecommerce_nutritional_products
Before: 'mysite/*'
After: 'framework/*','cms/*', 'ecommerce/*'
---


ProductGroup:
  extensions:
    - NutriHolderProductDataExtension

ProductConfigModelAdmin:
  managed_models:
    - NutriHolder


---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - NutriHolderProductDataExtension
